/*
 * Mercantile API
 * Programmatic access to the Mercantile service
 *
 * OpenAPI spec version: v1
 * Contact: gurleen.singh@drexel.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercantileApi);
  }
}(this, function(expect, MercantileApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CartItem', function() {
      beforeEach(function() {
        instance = new MercantileApi.CartItem();
      });

      it('should create an instance of CartItem', function() {
        // TODO: update the code to test CartItem
        expect(instance).to.be.a(MercantileApi.CartItem);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property product (base name: "product")', function() {
        // TODO: update the code to test the property product
        expect(instance).to.have.property('product');
        // expect(instance.product).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property itemTotal (base name: "item_total")', function() {
        // TODO: update the code to test the property itemTotal
        expect(instance).to.have.property('itemTotal');
        // expect(instance.itemTotal).to.be(expectedValueLiteral);
      });

    });
  });

}));
