/*
 * Mercantile API
 * Programmatic access to the Mercantile service
 *
 * OpenAPI spec version: v1
 * Contact: gurleen.singh@drexel.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercantileApi);
  }
}(this, function(expect, MercantileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercantileApi.AddressApi();
  });

  describe('(package)', function() {
    describe('AddressApi', function() {
      describe('addressCreate', function() {
        it('should call addressCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for addressCreate call and complete the assertions
          /*
          var data = new MercantileApi.Address();
          data.address = "";
          data.city = "";
          data.state = "";

          instance.addressCreate(data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Address);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.state).to.be.a('string');
            expect(data.state).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addressDelete', function() {
        it('should call addressDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for addressDelete call
          /*
          var id = "id_example";

          instance.addressDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addressList', function() {
        it('should call addressList successfully', function(done) {
          // TODO: uncomment, update parameter values for addressList call and complete the assertions
          /*
          var opts = {};
          opts.page = 56;

          instance.addressList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.InlineResponse200);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be(0);
            expect(data.next).to.be.a('string');
            expect(data.next).to.be("");
            expect(data.previous).to.be.a('string');
            expect(data.previous).to.be("");
            {
              let dataCtr = data.results;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.Address);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.address).to.be.a('string');
                expect(data.address).to.be("");
                expect(data.city).to.be.a('string');
                expect(data.city).to.be("");
                expect(data.state).to.be.a('string');
                expect(data.state).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addressPartialUpdate', function() {
        it('should call addressPartialUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for addressPartialUpdate call and complete the assertions
          /*
          var id = "id_example";
          var data = new MercantileApi.Address();
          data.address = "";
          data.city = "";
          data.state = "";

          instance.addressPartialUpdate(id, data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Address);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.state).to.be.a('string');
            expect(data.state).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addressRead', function() {
        it('should call addressRead successfully', function(done) {
          // TODO: uncomment, update parameter values for addressRead call and complete the assertions
          /*
          var id = "id_example";

          instance.addressRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Address);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.state).to.be.a('string');
            expect(data.state).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('addressUpdate', function() {
        it('should call addressUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for addressUpdate call and complete the assertions
          /*
          var id = "id_example";
          var data = new MercantileApi.Address();
          data.address = "";
          data.city = "";
          data.state = "";

          instance.addressUpdate(id, data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Address);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.address).to.be.a('string');
            expect(data.address).to.be("");
            expect(data.city).to.be.a('string');
            expect(data.city).to.be("");
            expect(data.state).to.be.a('string');
            expect(data.state).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
