/*
 * Mercantile API
 * Programmatic access to the Mercantile service
 *
 * OpenAPI spec version: v1
 * Contact: gurleen.singh@drexel.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercantileApi);
  }
}(this, function(expect, MercantileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercantileApi.CartApi();
  });

  describe('(package)', function() {
    describe('CartApi', function() {
      describe('cartCreate', function() {
        it('should call cartCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for cartCreate call and complete the assertions
          /*
          var data = new MercantileApi.CartItem();
          data.product = 0;
          data.amount = 0;

          instance.cartCreate(data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.CartItem);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.product).to.be.a('number');
            expect(data.product).to.be(0);
            expect(data.amount).to.be.a('number');
            expect(data.amount).to.be(0);
            expect(data.itemTotal).to.be.a('string');
            expect(data.itemTotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartDelete', function() {
        it('should call cartDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for cartDelete call
          /*
          var id = "id_example";

          instance.cartDelete(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartList', function() {
        it('should call cartList successfully', function(done) {
          // TODO: uncomment, update parameter values for cartList call and complete the assertions
          /*
          var opts = {};
          opts.page = 56;

          instance.cartList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.InlineResponse2001);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be(0);
            expect(data.next).to.be.a('string');
            expect(data.next).to.be("");
            expect(data.previous).to.be.a('string');
            expect(data.previous).to.be("");
            {
              let dataCtr = data.results;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.CartItem);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.product).to.be.a('number');
                expect(data.product).to.be(0);
                expect(data.amount).to.be.a('number');
                expect(data.amount).to.be(0);
                expect(data.itemTotal).to.be.a('string');
                expect(data.itemTotal).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartPartialUpdate', function() {
        it('should call cartPartialUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for cartPartialUpdate call and complete the assertions
          /*
          var id = "id_example";
          var data = new MercantileApi.CartItem();
          data.product = 0;
          data.amount = 0;

          instance.cartPartialUpdate(id, data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.CartItem);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.product).to.be.a('number');
            expect(data.product).to.be(0);
            expect(data.amount).to.be.a('number');
            expect(data.amount).to.be(0);
            expect(data.itemTotal).to.be.a('string');
            expect(data.itemTotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartRead', function() {
        it('should call cartRead successfully', function(done) {
          // TODO: uncomment, update parameter values for cartRead call and complete the assertions
          /*
          var id = "id_example";

          instance.cartRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.CartItem);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.product).to.be.a('number');
            expect(data.product).to.be(0);
            expect(data.amount).to.be.a('number');
            expect(data.amount).to.be(0);
            expect(data.itemTotal).to.be.a('string');
            expect(data.itemTotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartUpdate', function() {
        it('should call cartUpdate successfully', function(done) {
          // TODO: uncomment, update parameter values for cartUpdate call and complete the assertions
          /*
          var id = "id_example";
          var data = new MercantileApi.CartItem();
          data.product = 0;
          data.amount = 0;

          instance.cartUpdate(id, data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.CartItem);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.product).to.be.a('number');
            expect(data.product).to.be(0);
            expect(data.amount).to.be.a('number');
            expect(data.amount).to.be(0);
            expect(data.itemTotal).to.be.a('string');
            expect(data.itemTotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
