/*
 * Mercantile API
 * Programmatic access to the Mercantile service
 *
 * OpenAPI spec version: v1
 * Contact: gurleen.singh@drexel.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercantileApi);
  }
}(this, function(expect, MercantileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercantileApi.ImagesApi();
  });

  describe('(package)', function() {
    describe('ImagesApi', function() {
      describe('imagesList', function() {
        it('should call imagesList successfully', function(done) {
          // TODO: uncomment, update parameter values for imagesList call and complete the assertions
          /*
          var opts = {};
          opts.page = 56;

          instance.imagesList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.InlineResponse2002);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be(0);
            expect(data.next).to.be.a('string');
            expect(data.next).to.be("");
            expect(data.previous).to.be.a('string');
            expect(data.previous).to.be("");
            {
              let dataCtr = data.results;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.ProductImage);
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.image).to.be.a('string');
                expect(data.image).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('imagesRead', function() {
        it('should call imagesRead successfully', function(done) {
          // TODO: uncomment, update parameter values for imagesRead call and complete the assertions
          /*
          var id = 56;

          instance.imagesRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.ProductImage);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.image).to.be.a('string');
            expect(data.image).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
