/*
 * Mercantile API
 * Programmatic access to the Mercantile service
 *
 * OpenAPI spec version: v1
 * Contact: gurleen.singh@drexel.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercantileApi);
  }
}(this, function(expect, MercantileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercantileApi.OrderApi();
  });

  describe('(package)', function() {
    describe('OrderApi', function() {
      describe('orderConfirm', function() {
        it('should call orderConfirm successfully', function(done) {
          // TODO: uncomment, update parameter values for orderConfirm call and complete the assertions
          /*
          var id = "id_example";
          var data = new MercantileApi.Order();
          data.address = 0;

          instance.orderConfirm(id, data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Order);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.address).to.be.a('number');
            expect(data.address).to.be(0);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.CartItem);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.product).to.be.a('number');
                expect(data.product).to.be(0);
                expect(data.amount).to.be.a('number');
                expect(data.amount).to.be(0);
                expect(data.itemTotal).to.be.a('string');
                expect(data.itemTotal).to.be("");

                      }
            }
            expect(data.subtotal).to.be.a('string');
            expect(data.subtotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('orderCreate', function() {
        it('should call orderCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for orderCreate call and complete the assertions
          /*
          var data = new MercantileApi.Order();
          data.address = 0;

          instance.orderCreate(data, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Order);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.address).to.be.a('number');
            expect(data.address).to.be(0);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.CartItem);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.product).to.be.a('number');
                expect(data.product).to.be(0);
                expect(data.amount).to.be.a('number');
                expect(data.amount).to.be(0);
                expect(data.itemTotal).to.be.a('string');
                expect(data.itemTotal).to.be("");

                      }
            }
            expect(data.subtotal).to.be.a('string');
            expect(data.subtotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('orderList', function() {
        it('should call orderList successfully', function(done) {
          // TODO: uncomment, update parameter values for orderList call and complete the assertions
          /*
          var opts = {};
          opts.page = 56;

          instance.orderList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.InlineResponse2003);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be(0);
            expect(data.next).to.be.a('string');
            expect(data.next).to.be("");
            expect(data.previous).to.be.a('string');
            expect(data.previous).to.be("");
            {
              let dataCtr = data.results;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.Order);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.status).to.be.a('string');
                expect(data.status).to.be("");
                expect(data.address).to.be.a('number');
                expect(data.address).to.be(0);
                {
                  let dataCtr = data.items;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(MercantileApi.CartItem);
                    expect(data.id).to.be.a('number');
                    expect(data.id).to.be(0);
                    expect(data.product).to.be.a('number');
                    expect(data.product).to.be(0);
                    expect(data.amount).to.be.a('number');
                    expect(data.amount).to.be(0);
                    expect(data.itemTotal).to.be.a('string');
                    expect(data.itemTotal).to.be("");
    
                          }
                }
                expect(data.subtotal).to.be.a('string');
                expect(data.subtotal).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('orderRead', function() {
        it('should call orderRead successfully', function(done) {
          // TODO: uncomment, update parameter values for orderRead call and complete the assertions
          /*
          var id = "id_example";

          instance.orderRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Order);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.address).to.be.a('number');
            expect(data.address).to.be(0);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.CartItem);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.product).to.be.a('number');
                expect(data.product).to.be(0);
                expect(data.amount).to.be.a('number');
                expect(data.amount).to.be(0);
                expect(data.itemTotal).to.be.a('string');
                expect(data.itemTotal).to.be("");

                      }
            }
            expect(data.subtotal).to.be.a('string');
            expect(data.subtotal).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
