/*
 * Mercantile API
 * Programmatic access to the Mercantile service
 *
 * OpenAPI spec version: v1
 * Contact: gurleen.singh@drexel.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MercantileApi);
  }
}(this, function(expect, MercantileApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MercantileApi.ProductApi();
  });

  describe('(package)', function() {
    describe('ProductApi', function() {
      describe('productList', function() {
        it('should call productList successfully', function(done) {
          // TODO: uncomment, update parameter values for productList call and complete the assertions
          /*
          var opts = {};
          opts.page = 56;

          instance.productList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.InlineResponse2004);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be(0);
            expect(data.next).to.be.a('string');
            expect(data.next).to.be("");
            expect(data.previous).to.be.a('string');
            expect(data.previous).to.be("");
            {
              let dataCtr = data.results;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MercantileApi.Product);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("");
                expect(data.brand).to.be.a('string');
                expect(data.brand).to.be("");
                expect(data.description).to.be.a('string');
                expect(data.description).to.be("");
                expect(data.price).to.be.a('string');
                expect(data.price).to.be("");
                expect(data.firstImage).to.be.a('string');
                expect(data.firstImage).to.be("");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('productRead', function() {
        it('should call productRead successfully', function(done) {
          // TODO: uncomment, update parameter values for productRead call and complete the assertions
          /*
          var id = 56;

          instance.productRead(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MercantileApi.Product);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(0);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.brand).to.be.a('string');
            expect(data.brand).to.be("");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.price).to.be.a('string');
            expect(data.price).to.be("");
            expect(data.firstImage).to.be.a('string');
            expect(data.firstImage).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
